version: '3.8'

services:
  module5hw2:
    container_name: module5hw2.catalog.api
    build:
      context: .
      dockerfile: Module5HW2/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - PathBase=http://www.alevelwebsite.com:5000
    ports:
      - 5000:5000
networks:
  dockernet:
    external: true